name: TrollPlugin
version: '${project.version}'
main: org.gutenn.trollplugin.TrollPlugin
api-version: '1.20'

commands:
  setwspawn:
    permission: permissions.setwspawn
permissions:
  permissions.setwspawn:
    default: op


